#!/bin/sh
[ -e /etc/crontabs/root ] && exit 0
cat << "IOF" >> /etc/crontabs/root
# Reboot at 4:30am every day
# Note: To avoid infinite reboot loop, wait 70 seconds
# and touch a file in /etc so clock will be set
# properly to 4:31 on reboot before cron starts.
19 4 * * * sleep 70 && touch /etc/banner && reboot
IOF
