name: 'Build OpenWrt'

on:
  workflow_dispatch:

env:
  OPENWRT_REPOSITORY: https://github.com/openwrt/openwrt
  PREINSTALL_SCRIPT: pre-install-feeds.sh
  POSTINSTALL_SCRIPT: post-install-feeds.sh

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/Checkout@v3

      - name: Build System Setup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt -yqq update
          sudo -E apt -yqq install $(cat ubuntu-dependencies.txt)
          sudo -E apt -yqq autoremove --purge

      - name: Fetch OpenWrt Sources
        run: |
          LATEST_STABLE_BRANCH=$(git ls-remote --heads ${OPENWRT_REPOSITORY} | tail -n1 | awk -F '/' '{print $3}')
          echo "OPENWRT_VERSION=${LATEST_STABLE_BRANCH}" >> $GITHUB_ENV
          #git clone -q --depth 1 --single-branch ${OPENWRT_REPOSITORY} -b ${LATEST_STABLE_BRANCH} openwrt
          git clone -q --depth 1 --single-branch ${OPENWRT_REPOSITORY} -b master openwrt

      - name: Run Pre-install Feeds Script
        run: |
          [[ -e ${PREINSTALL_SCRIPT} ]]
          cd openwrt
          chmod +x ${GITHUB_WORKSPACE}/${PREINSTALL_SCRIPT}
          ${GITHUB_WORKSPACE}/${PREINSTALL_SCRIPT}
          cp -rf ../patch/* .

      - name: Update The Feeds
        run: cd openwrt && ./scripts/feeds update -a

      - name: Install The Feeds
        run: cd openwrt && ./scripts/feeds install -a

      - name: Get The Official Config
        run: |
          cd openwrt
          LATEST_TAG=$(curl -s https://api.github.com/repos/openwrt/openwrt/releases/latest  | grep "tag_name" | awk '{print $2}' | tr -d '",\n' | cut -c 2-)
          #wget https://downloads.openwrt.org/releases/${LATEST_TAG}/targets/ramips/mt76x8/config.buildinfo -O .config
          #grep "CONFIG_TARGET_DEVICE_ramips" .config | grep -v "xiaomi" | sed 's/=y/=n/g' > exclude-device
          #sed -i '/CONFIG_TARGET_DEVICE/{/xiaomi/!d}' .config
          #cat exclude-device >> .config
          # write `diffconfig` to `.config`
          cp diffconfig .config

      - name: Run Post-install Feeds Script
        run: |
          [[ -e ${POSTINSTALL_SCRIPT} ]]
          cd openwrt
          chmod +x ${GITHUB_WORKSPACE}/${POSTINSTALL_SCRIPT}
          ${GITHUB_WORKSPACE}/${POSTINSTALL_SCRIPT}

      - name: Build The Firmware Image
        id: build
        run: |
          cd openwrt
          make -j $(($(nproc)+1)) defconfig download clean world || make -j1 V=s
          #echo "build_tag=${OPENWRT_VERSION}-ramips-mt76x8" >> ${GITHUB_OUTPUT}
          echo "build_tag=snapshot-$(cat bin/targets/*/*/version*)" >> ${GITHUB_OUTPUT}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Upload The Firmware Image
        uses: ncipollo/release-action@main
        if: ${{ steps.build.outputs.status }} == 'success' && !cancelled()
        with:
          tag: ${{ steps.build.outputs.build_tag }}
          artifacts: openwrt/bin/targets/*/*/*sysupgrade.bin
          allowUpdates: true
          token: ${{ secrets.RELEASE_TOKEN }}

