name: 'Build OpenWrt'

on:
  workflow_dispatch:

env:
  OPENWRT_REPOSITORY: https://github.com/openwrt/openwrt
  PREINSTALL_SCRIPT: pre-install-feeds.sh
  POSTINSTALL_SCRIPT: post-install-feeds.sh

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/Checkout@v3

      - name: Build System Setup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt -y update
          sudo -E apt -y install $(cat ubuntu-dependencies.txt)
          sudo -E apt -y autoremove --purge

      - name: Fetch OpenWrt Sources
        run: |
          LATEST_STABLE_BRANCH=$(git ls-remote --heads ${OPENWRT_REPOSITORY} | tail -n1 | awk -F '/' '{print $3}')
          echo "OPENWRT_VERSION=${LATEST_STABLE_BRANCH}" >> $GITHUB_ENV
          git clone -q --depth 1 --single-branch ${OPENWRT_REPOSITORY} -b ${LATEST_STABLE_BRANCH} openwrt

      - name: Run Pre-install Feeds Script
        run: |
          [[ -e ${PREINSTALL_SCRIPT} ]]
          cd openwrt
          chmod +x ${GITHUB_WORKSPACE}/${PREINSTALL_SCRIPT}
          ${GITHUB_WORKSPACE}/${PREINSTALL_SCRIPT}

      - name: Update The Feeds
        run: cd openwrt && ./scripts/feeds update -a

      - name: Install The Feeds
        run: cd openwrt && ./scripts/feeds install -a

      - name: Get The Official Config
        run: |
          cd openwrt
          wget https://downloads.openwrt.org/releases/${OPENWRT_VERSION}/targets/ramips/mt76x8/config.buildinfo -O .config
          sed -i '/CONFIG_TARGET_DEVICE/{/xiaomi/!d}' .config

      - name: Run Post-install Feeds Script
        run: |
          [[ -e ${POSTINSTALL_SCRIPT} ]]
          cd openwrt
          chmod +x ${GITHUB_WORKSPACE}/${POSTINSTALL_SCRIPT}
          ${GITHUB_WORKSPACE}/${POSTINSTALL_SCRIPT}

      - name: Build The Firmware Image
        id: build
        run: |
          cd openwrt
          make -j $(($(nproc)+1)) defconfig download clean world || make -j1 V=s
          echo "build_tag=openwrt-${OPENWRT_VERSION}-ramips-mt76x8" >> ${GITHUB_OUTPUT}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Upload The Firmware Image
        uses: ncipollo/releases-action@main
        if: ${{ steps.build.outputs.status }} == 'success' && !cancelled()
        with:
          tag: ${{ steps.compile.outputs.build_tag }}
          artifacts: openwrt/bin/targets/*/*/*
          allowUpdates: true
          token: ${{ secrets.RELEASE_TOKEN }}

